# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Seed Configuration

# Model Form Field configuration
form: $/davox/faker/models/seed/fields.yaml

# Model Class name
modelClass: Davox\Faker\Models\Seed

# Default redirect location
defaultRedirect: davox/faker/seeds

# Create page
create:
    title: backend::lang.form.create_title
    redirect: davox/faker/seeds/update/:id
    redirectClose: davox/faker/seeds

# Update page
update:
    title: backend::lang.form.update_title
    redirect: davox/faker/seeds
    redirectClose: davox/faker/seeds

# Preview page
preview:
    title: backend::lang.form.preview_title